# serverless.yml
service: serverless-nodejs-app
useDotenv: true
provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: us-west-1
functions:
    app:
        handler: app.server # reference the file and exported method
        events: # events trigger lambda functions
            - http: # this is an API Gateway HTTP event trigger
                  path: /
                  method: ANY
                  cors: true
            - http: # all routes get proxied to the Express router
                  path: /{proxy+}
                  method: ANY
                  cors: true

plugins:
  - serverless-offline
